name: Pruebas unitarias con validacion
on: 
  push:
    branches: [ develop ]
jobs:
  job1:
    name: Pruebas v3
    runs-on: ubuntu-latest
    outputs:
      salida: ${{ steps.imprimir.outputs.respuesta }}
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuracion de entorno python
      uses: actions/setup-python@v2
      with:
          python-version: '3.7'
    - name: Instalacion de librerias y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest -v tests/test_persona.py
    - name: validar resultado con errores
      if: ${{ failure() }}
      env: 
        MENSAJE_ERROR: Una o varias pruebas fallaron
      run: echo "::set-output name=respuesta::${MENSAJE_EXITOSO}"
    - name: Validar resultados sin errores
      if: ${{ success() }}
      env:
        MENSAJE_EXITO: Todas las pruebas fueron exitosas
      run: echo "::set-output name=respuesta::${MENSAJE_EXITO}"
    - name: CÃ¡lcula de cubrimiento
      id: cubrimiento
      run: |
          coverage run -m unittest tests/test_persona.py
          coverage report -m