name: Pruebas unitarias
on:
  push:
    branches: [ develop ]
jobs:
  job1:
    name: Pruebas
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
      with:
          python-version: '3.7'
    - name: Instalacion de librerias y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requriments.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest -v tests/test_persona.py
      - name: CÃ¡lculo de cubrimiento
        id: cubrimiento
        run: |
          coverage run -m unittest tests/test_persona.py
          coverage report -m
        
